@ComicFuryAPI_HostAddress = http://localhost:5261

###

GET {{ComicFuryAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ComicFuryAPI_HostAddress}}/profileinfo/
Accept: application/json
Content-Type: 

{
   "username": "ThatOneAceGuy"
}
###
@Request_UserName = SaltnPepperBunny

GET {{ComicFuryAPI_HostAddress}}/{{Request_UserName}}/author

###